//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashInTerminalWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashInTerminalWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _1365266245_home {
            get {
                object obj = ResourceManager.GetObject("_1365266245_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonent code.
        /// </summary>
        public static string AbonentCode {
            get {
                return ResourceManager.GetString("AbonentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        public static string AbonentDebt {
            get {
                return ResourceManager.GetString("AbonentDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AbonentName {
            get {
                return ResourceManager.GetString("AbonentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab nömrəsi.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab nömrəsini təkrarlayın.
        /// </summary>
        public static string AccountNumberRetype {
            get {
                return ResourceManager.GetString("AccountNumberRetype", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap backspace32 {
            get {
                object obj = ResourceManager.GetObject("backspace32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartın son 8 rəqəmi.
        /// </summary>
        public static string BolLastFour {
            get {
                return ResourceManager.GetString("BolLastFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 8 rəqəmi təkrarlayın.
        /// </summary>
        public static string BolLastFourRetype {
            get {
                return ResourceManager.GetString("BolLastFourRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonlandır.
        /// </summary>
        public static string ButtonActivation {
            get {
                return ResourceManager.GetString("ButtonActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İdeal, Bolkart, MyBrands, Hissə ödənişlər.
        /// </summary>
        public static string ButtonBolCard {
            get {
                return ResourceManager.GetString("ButtonBolCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müştəri kodu ilə.
        /// </summary>
        public static string ButtonClientNumber {
            get {
                return ResourceManager.GetString("ButtonClientNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab və Şəxsiyyət vəsiqəsilə.
        /// </summary>
        public static string ButtonCreditNumberAndPasport {
            get {
                return ResourceManager.GetString("ButtonCreditNumberAndPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonlandır.
        /// </summary>
        public static string ButtonEncashmentFinish {
            get {
                return ResourceManager.GetString("ButtonEncashmentFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çekin çapı.
        /// </summary>
        public static string ButtonEncashmentPrint {
            get {
                return ResourceManager.GetString("ButtonEncashmentPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödəniş et.
        /// </summary>
        public static string ButtonMoneyNext {
            get {
                return ResourceManager.GetString("ButtonMoneyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonlandır.
        /// </summary>
        public static string ButtonSuccessNext {
            get {
                return ResourceManager.GetString("ButtonSuccessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınaq.
        /// </summary>
        public static string ButtonTest {
            get {
                return ResourceManager.GetString("ButtonTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müştəri kodu.
        /// </summary>
        public static string ClientCode {
            get {
                return ResourceManager.GetString("ClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müştəri kodu təkrarlayın.
        /// </summary>
        public static string ClientCodeRetype {
            get {
                return ResourceManager.GetString("ClientCodeRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditin məbləği.
        /// </summary>
        public static string CreditAmount {
            get {
                return ResourceManager.GetString("CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditin balansı.
        /// </summary>
        public static string CreditAmountLeft {
            get {
                return ResourceManager.GetString("CreditAmountLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödəniləcək məbləğ.
        /// </summary>
        public static string CreditAmountToPay {
            get {
                return ResourceManager.GetString("CreditAmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit bağlıdır.
        /// </summary>
        public static string CreditClosed {
            get {
                return ResourceManager.GetString("CreditClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditin tarixi.
        /// </summary>
        public static string CreditDate {
            get {
                return ResourceManager.GetString("CreditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit hələ açıqdır.
        /// </summary>
        public static string CreditOpen {
            get {
                return ResourceManager.GetString("CreditOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valyuta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.A.A..
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilmiş telefon nömrəniz:.
        /// </summary>
        public static string LabelAcceptPhoneNumber {
            get {
                return ResourceManager.GetString("LabelAcceptPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasiyanın kodu.
        /// </summary>
        public static string LabelActivation {
            get {
                return ResourceManager.GetString("LabelActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal aktivasiya tələb edir!.
        /// </summary>
        public static string LabelActivation1 {
            get {
                return ResourceManager.GetString("LabelActivation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string LabelBack {
            get {
                return ResourceManager.GetString("LabelBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelClientCode {
            get {
                return ResourceManager.GetString("LabelClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əskinaz qəbuledicinin portu.
        /// </summary>
        public static string LabelCom {
            get {
                return ResourceManager.GetString("LabelCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.4% Əməliyyatın komissiyası.
        /// </summary>
        public static string LabelComission {
            get {
                return ResourceManager.GetString("LabelComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnkassasiya Rejimi.
        /// </summary>
        public static string LabelEncashmentMode {
            get {
                return ResourceManager.GetString("LabelEncashmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qəbul olunub.
        /// </summary>
        public static string LabelInput {
            get {
                return ResourceManager.GetString("LabelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış nömrə.
        /// </summary>
        public static string LabelInvalidNumber {
            get {
                return ResourceManager.GetString("LabelInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrəli.
        /// </summary>
        public static string LabelNext {
            get {
                return ResourceManager.GetString("LabelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal müvəqqəti olaraq işləmir. Buna görə sizdən üzr istəyirik.
        /// </summary>
        public static string LabelOutOfOrder {
            get {
                return ResourceManager.GetString("LabelOutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Telefon nömrəsi.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit Sifarişiniz qəbul olunub. 
        ///Yaxın zamanda sizinlə 
        ///əlaqə saxlanılacaq. 
        ///
        ///Təşəkkür edirik.
        /// </summary>
        public static string LabelSuccessCreditRequest {
            get {
                return ResourceManager.GetString("LabelSuccessCreditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşəkkürlər!.
        /// </summary>
        public static string LabelSuccessWelcome {
            get {
                return ResourceManager.GetString("LabelSuccessWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal №.
        /// </summary>
        public static string LabelTerminal {
            get {
                return ResourceManager.GetString("LabelTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qəbul olunub.
        /// </summary>
        public static string LabelTotal {
            get {
                return ResourceManager.GetString("LabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa gözləyin.
        /// </summary>
        public static string LabelWait {
            get {
                return ResourceManager.GetString("LabelWait", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeyr.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasportun seriya və nömrəsi.
        /// </summary>
        public static string PasportInfo {
            get {
                return ResourceManager.GetString("PasportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasport №.
        /// </summary>
        public static string PasportNumber {
            get {
                return ResourceManager.GetString("PasportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to təkrarlayın.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Service_unavailable {
            get {
                object obj = ResourceManager.GetObject("Service_unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xidmət müvəqqəti olaraq işləmir. Buna görə sizdən üzr istəyirik.
        /// </summary>
        public static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əməliyyat ID.
        /// </summary>
        public static string TransactionID {
            get {
                return ResourceManager.GetString("TransactionID", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Unavailable {
            get {
                object obj = ResourceManager.GetObject("Unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bəli.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
