//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashInCore.PaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bankofbaku.com/PaymentService", ConfigurationName="PaymentService.PaymentService")]
    public interface PaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/GetInfo", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/GetInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.ServiceInfoResult GetInfo(string username, string password, CashInCore.PaymentService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/GetInfoPure", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/GetInfoPureResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.ServiceInfoResult GetInfoPure(string username, string password, CashInCore.PaymentService.PureInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/InsertPayment", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/InsertPaymentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.InfoResult InsertPayment(string username, string password, string signature, CashInCore.PaymentService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/InsertPaymentPure", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/InsertPaymentPureResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.InfoResult InsertPaymentPure(string username, string password, string signature, CashInCore.PaymentService.PurePaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/ListServices", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/ListServicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.GetServicesResult ListServices(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/ListCategories", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/ListCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.CategoriesResult ListCategories(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/PaymentService/GetService", ReplyAction="http://www.bankofbaku.com/PaymentService/PaymentService/GetServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        CashInCore.PaymentService.GetServicesResult GetService(string username, string password, int serviceId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class PaymentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int service_idField;
        
        private string service_nameField;
        
        private string service_sub_nameField;
        
        private string paypoint_payment_typeField;
        
        private HistoryField[] fieldsField;
        
        private string currencyField;
        
        private int amountField;
        
        private string payment_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int service_id {
            get {
                return this.service_idField;
            }
            set {
                this.service_idField = value;
                this.RaisePropertyChanged("service_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                this.service_nameField = value;
                this.RaisePropertyChanged("service_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string service_sub_name {
            get {
                return this.service_sub_nameField;
            }
            set {
                this.service_sub_nameField = value;
                this.RaisePropertyChanged("service_sub_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string paypoint_payment_type {
            get {
                return this.paypoint_payment_typeField;
            }
            set {
                this.paypoint_payment_typeField = value;
                this.RaisePropertyChanged("paypoint_payment_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public HistoryField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string payment_id {
            get {
                return this.payment_idField;
            }
            set {
                this.payment_idField = value;
                this.RaisePropertyChanged("payment_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class HistoryField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PurePaymentInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class PureInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int service_idField;
        
        private string service_nameField;
        
        private HistoryField[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int service_id {
            get {
                return this.service_idField;
            }
            set {
                this.service_idField = value;
                this.RaisePropertyChanged("service_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                this.service_nameField = value;
                this.RaisePropertyChanged("service_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HistoryField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class PurePaymentInfo : PureInfo {
        
        private string currencyField;
        
        private int amountField;
        
        private string payment_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string payment_id {
            get {
                return this.payment_idField;
            }
            set {
                this.payment_idField = value;
                this.RaisePropertyChanged("payment_id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class PaymentCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string name_enField;
        
        private string name_ruField;
        
        private string name_azField;
        
        private Service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name_en {
            get {
                return this.name_enField;
            }
            set {
                this.name_enField = value;
                this.RaisePropertyChanged("name_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name_az {
            get {
                return this.name_azField;
            }
            set {
                this.name_azField = value;
                this.RaisePropertyChanged("name_az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("services");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class Service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string name_azField;
        
        private string name_enField;
        
        private string name_ruField;
        
        private string sub_nameField;
        
        private string paypoint_payment_typeField;
        
        private string assembly_idField;
        
        private int typeField;
        
        private bool fixed_amountField;
        
        private int category_idField;
        
        private int min_amountField;
        
        private int max_amountField;
        
        private FixedAmount[] amounts_listField;
        
        private ServiceField[] service_fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name_az {
            get {
                return this.name_azField;
            }
            set {
                this.name_azField = value;
                this.RaisePropertyChanged("name_az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name_en {
            get {
                return this.name_enField;
            }
            set {
                this.name_enField = value;
                this.RaisePropertyChanged("name_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sub_name {
            get {
                return this.sub_nameField;
            }
            set {
                this.sub_nameField = value;
                this.RaisePropertyChanged("sub_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string paypoint_payment_type {
            get {
                return this.paypoint_payment_typeField;
            }
            set {
                this.paypoint_payment_typeField = value;
                this.RaisePropertyChanged("paypoint_payment_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string assembly_id {
            get {
                return this.assembly_idField;
            }
            set {
                this.assembly_idField = value;
                this.RaisePropertyChanged("assembly_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool fixed_amount {
            get {
                return this.fixed_amountField;
            }
            set {
                this.fixed_amountField = value;
                this.RaisePropertyChanged("fixed_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int category_id {
            get {
                return this.category_idField;
            }
            set {
                this.category_idField = value;
                this.RaisePropertyChanged("category_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int min_amount {
            get {
                return this.min_amountField;
            }
            set {
                this.min_amountField = value;
                this.RaisePropertyChanged("min_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int max_amount {
            get {
                return this.max_amountField;
            }
            set {
                this.max_amountField = value;
                this.RaisePropertyChanged("max_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public FixedAmount[] amounts_list {
            get {
                return this.amounts_listField;
            }
            set {
                this.amounts_listField = value;
                this.RaisePropertyChanged("amounts_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service_field")]
        public ServiceField[] service_fields {
            get {
                return this.service_fieldsField;
            }
            set {
                this.service_fieldsField = value;
                this.RaisePropertyChanged("service_fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class FixedAmount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int service_idField;
        
        private int amountField;
        
        private string name_azField;
        
        private string name_enField;
        
        private string name_ruField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int service_id {
            get {
                return this.service_idField;
            }
            set {
                this.service_idField = value;
                this.RaisePropertyChanged("service_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name_az {
            get {
                return this.name_azField;
            }
            set {
                this.name_azField = value;
                this.RaisePropertyChanged("name_az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name_en {
            get {
                return this.name_enField;
            }
            set {
                this.name_enField = value;
                this.RaisePropertyChanged("name_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class ServiceField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int service_idField;
        
        private string nameField;
        
        private string name_azField;
        
        private string name_enField;
        
        private string name_ruField;
        
        private string service_nameField;
        
        private string typeField;
        
        private string regexpField;
        
        private string default_valueField;
        
        private int order_numField;
        
        private ServiceEnum[] field_valuesField;
        
        private string normalize_regexpField;
        
        private string normalize_patternField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int service_id {
            get {
                return this.service_idField;
            }
            set {
                this.service_idField = value;
                this.RaisePropertyChanged("service_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name_az {
            get {
                return this.name_azField;
            }
            set {
                this.name_azField = value;
                this.RaisePropertyChanged("name_az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name_en {
            get {
                return this.name_enField;
            }
            set {
                this.name_enField = value;
                this.RaisePropertyChanged("name_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                this.service_nameField = value;
                this.RaisePropertyChanged("service_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string regexp {
            get {
                return this.regexpField;
            }
            set {
                this.regexpField = value;
                this.RaisePropertyChanged("regexp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string default_value {
            get {
                return this.default_valueField;
            }
            set {
                this.default_valueField = value;
                this.RaisePropertyChanged("default_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int order_num {
            get {
                return this.order_numField;
            }
            set {
                this.order_numField = value;
                this.RaisePropertyChanged("order_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public ServiceEnum[] field_values {
            get {
                return this.field_valuesField;
            }
            set {
                this.field_valuesField = value;
                this.RaisePropertyChanged("field_values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string normalize_regexp {
            get {
                return this.normalize_regexpField;
            }
            set {
                this.normalize_regexpField = value;
                this.RaisePropertyChanged("normalize_regexp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string normalize_pattern {
            get {
                return this.normalize_patternField;
            }
            set {
                this.normalize_patternField = value;
                this.RaisePropertyChanged("normalize_pattern");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class ServiceEnum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int field_idField;
        
        private string nameField;
        
        private string name_azField;
        
        private string name_enField;
        
        private string name_ruField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int field_id {
            get {
                return this.field_idField;
            }
            set {
                this.field_idField = value;
                this.RaisePropertyChanged("field_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name_az {
            get {
                return this.name_azField;
            }
            set {
                this.name_azField = value;
                this.RaisePropertyChanged("name_az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name_en {
            get {
                return this.name_enField;
            }
            set {
                this.name_enField = value;
                this.RaisePropertyChanged("name_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class ServiceInfoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string debt_typeField;
        
        private int amountField;
        
        private bool can_payField;
        
        private bool creditField;
        
        private bool can_depositField;
        
        private bool is_amount_changableField;
        
        private int tariffField;
        
        private int codeField;
        
        private int max_amountField;
        
        private int min_amountField;
        
        private int[] fixed_amountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string debt_type {
            get {
                return this.debt_typeField;
            }
            set {
                this.debt_typeField = value;
                this.RaisePropertyChanged("debt_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool can_pay {
            get {
                return this.can_payField;
            }
            set {
                this.can_payField = value;
                this.RaisePropertyChanged("can_pay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool can_deposit {
            get {
                return this.can_depositField;
            }
            set {
                this.can_depositField = value;
                this.RaisePropertyChanged("can_deposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool is_amount_changable {
            get {
                return this.is_amount_changableField;
            }
            set {
                this.is_amount_changableField = value;
                this.RaisePropertyChanged("is_amount_changable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
                this.RaisePropertyChanged("tariff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int max_amount {
            get {
                return this.max_amountField;
            }
            set {
                this.max_amountField = value;
                this.RaisePropertyChanged("max_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int min_amount {
            get {
                return this.min_amountField;
            }
            set {
                this.min_amountField = value;
                this.RaisePropertyChanged("min_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fixed_amounts", Order=13)]
        public int[] fixed_amounts {
            get {
                return this.fixed_amountsField;
            }
            set {
                this.fixed_amountsField = value;
                this.RaisePropertyChanged("fixed_amounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class ServicesInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personField;
        
        private float debtField;
        
        private ServiceInfoItem[] valuesField;
        
        private bool is_availableField;
        
        private bool is_errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float debt {
            get {
                return this.debtField;
            }
            set {
                this.debtField = value;
                this.RaisePropertyChanged("debt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service_info_item")]
        public ServiceInfoItem[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool is_available {
            get {
                return this.is_availableField;
            }
            set {
                this.is_availableField = value;
                this.RaisePropertyChanged("is_available");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool is_error {
            get {
                return this.is_errorField;
            }
            set {
                this.is_errorField = value;
                this.RaisePropertyChanged("is_error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoriesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetServicesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InfoResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceInfoResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public abstract partial class BaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCodes codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ErrorCodes code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public enum ErrorCodes {
        
        /// <remarks/>
        Ok = 1,
        
        /// <remarks/>
        InvalidNumber = 2,
        
        /// <remarks/>
        InvalidParameters = 4,
        
        /// <remarks/>
        DublicatePaymentId = 8,
        
        /// <remarks/>
        InvalidCurrency = 16,
        
        /// <remarks/>
        UnknownError = 32,
        
        /// <remarks/>
        SystemError = 64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class CategoriesResult : BaseResult {
        
        private PaymentCategory[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PaymentCategory[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("Categories");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class GetServicesResult : BaseResult {
        
        private Service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public Service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("services");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class InfoResult : BaseResult {
        
        private string extended_descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string extended_description {
            get {
                return this.extended_descriptionField;
            }
            set {
                this.extended_descriptionField = value;
                this.RaisePropertyChanged("extended_description");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class ServiceInfoResult : BaseResult {
        
        private ServicesInfo service_infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServicesInfo service_info {
            get {
                return this.service_infoField;
            }
            set {
                this.service_infoField = value;
                this.RaisePropertyChanged("service_info");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentServiceChannel : CashInCore.PaymentService.PaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<CashInCore.PaymentService.PaymentService>, CashInCore.PaymentService.PaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CashInCore.PaymentService.ServiceInfoResult GetInfo(string username, string password, CashInCore.PaymentService.PaymentInfo info) {
            return base.Channel.GetInfo(username, password, info);
        }
        
        public CashInCore.PaymentService.ServiceInfoResult GetInfoPure(string username, string password, CashInCore.PaymentService.PureInfo info) {
            return base.Channel.GetInfoPure(username, password, info);
        }
        
        public CashInCore.PaymentService.InfoResult InsertPayment(string username, string password, string signature, CashInCore.PaymentService.PaymentInfo info) {
            return base.Channel.InsertPayment(username, password, signature, info);
        }
        
        public CashInCore.PaymentService.InfoResult InsertPaymentPure(string username, string password, string signature, CashInCore.PaymentService.PurePaymentInfo info) {
            return base.Channel.InsertPaymentPure(username, password, signature, info);
        }
        
        public CashInCore.PaymentService.GetServicesResult ListServices(string username, string password) {
            return base.Channel.ListServices(username, password);
        }
        
        public CashInCore.PaymentService.CategoriesResult ListCategories(string username, string password) {
            return base.Channel.ListCategories(username, password);
        }
        
        public CashInCore.PaymentService.GetServicesResult GetService(string username, string password, int serviceId) {
            return base.Channel.GetService(username, password, serviceId);
        }
    }
}
