//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashInTerminal.CashIn {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cashin/CashInService", ConfigurationName="CashIn.CashInServer")]
    public interface CashInServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/GetPublicKey", ReplyAction="http://cashin/CashInService/CashInServer/GetPublicKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPublicKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/InitTerminal", ReplyAction="http://cashin/CashInService/CashInServer/InitTerminalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.AuthResult InitTerminal(int terminalId, string authKey, string publicKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/Ping", ReplyAction="http://cashin/CashInService/CashInServer/PingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.PingResult Ping(CashInTerminal.CashIn.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/CommandReceived", ReplyAction="http://cashin/CashInService/CashInServer/CommandReceivedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.StandardResult CommandReceived(CashInTerminal.CashIn.StandardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/ListProducts", ReplyAction="http://cashin/CashInService/CashInServer/ListProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.ProductResult ListProducts(CashInTerminal.CashIn.StandardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/ListCurrencies", ReplyAction="http://cashin/CashInService/CashInServer/ListCurrenciesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.CurrenciesResult ListCurrencies(CashInTerminal.CashIn.StandardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/Payment", ReplyAction="http://cashin/CashInService/CashInServer/PaymentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.StandardResult Payment(CashInTerminal.CashIn.PaymentInfoByProducts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cashin/CashInService/CashInServer/Encashment", ReplyAction="http://cashin/CashInService/CashInServer/EncashmentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseMessage))]
        CashInTerminal.CashIn.StandardResult Encashment(CashInTerminal.CashIn.Encashment request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class AuthResult : StandardResult {
        
        private string publicKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PublicKey {
            get {
                return this.publicKeyField;
            }
            set {
                this.publicKeyField = value;
                this.RaisePropertyChanged("PublicKey");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrenciesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class StandardResult : BaseMessage {
        
        private ResultCodes resultCodesField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultCodes ResultCodes {
            get {
                return this.resultCodesField;
            }
            set {
                this.resultCodesField = value;
                this.RaisePropertyChanged("ResultCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public enum ResultCodes {
        
        /// <remarks/>
        Ok = 1,
        
        /// <remarks/>
        InvalidNumber = 2,
        
        /// <remarks/>
        InvalidParameters = 4,
        
        /// <remarks/>
        InvalidTerminal = 8,
        
        /// <remarks/>
        InvalidKey = 16,
        
        /// <remarks/>
        InvalidSignature = 32,
        
        /// <remarks/>
        UnknownError = 64,
        
        /// <remarks/>
        SystemError = 128,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandardRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Encashment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentInfoByProducts))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandardResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrenciesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public abstract partial class BaseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime systemTimeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime SystemTime {
            get {
                return this.systemTimeField;
            }
            set {
                this.systemTimeField = value;
                this.RaisePropertyChanged("SystemTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class Currency : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string isoNameField;
        
        private string nameField;
        
        private bool defaultCurrencyField;
        
        private decimal currencyRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IsoName {
            get {
                return this.isoNameField;
            }
            set {
                this.isoNameField = value;
                this.RaisePropertyChanged("IsoName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool DefaultCurrency {
            get {
                return this.defaultCurrencyField;
            }
            set {
                this.defaultCurrencyField = value;
                this.RaisePropertyChanged("DefaultCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal CurrencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
                this.RaisePropertyChanged("CurrencyRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private string nameField;
        
        private string nameAzField;
        
        private string nameRuField;
        
        private string nameEnField;
        
        private string assemblyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NameAz {
            get {
                return this.nameAzField;
            }
            set {
                this.nameAzField = value;
                this.RaisePropertyChanged("NameAz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NameRu {
            get {
                return this.nameRuField;
            }
            set {
                this.nameRuField = value;
                this.RaisePropertyChanged("NameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NameEn {
            get {
                return this.nameEnField;
            }
            set {
                this.nameEnField = value;
                this.RaisePropertyChanged("NameEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
                this.RaisePropertyChanged("Assembly");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Encashment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentInfoByProducts))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class StandardRequest : BaseMessage {
        
        private int terminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TerminalId {
            get {
                return this.terminalIdField;
            }
            set {
                this.terminalIdField = value;
                this.RaisePropertyChanged("TerminalId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class Encashment : StandardRequest {
        
        private int userIdField;
        
        private string[] currenciesField;
        
        private int[] amountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Currencies {
            get {
                return this.currenciesField;
            }
            set {
                this.currenciesField = value;
                this.RaisePropertyChanged("Currencies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] Amounts {
            get {
                return this.amountsField;
            }
            set {
                this.amountsField = value;
                this.RaisePropertyChanged("Amounts");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class PaymentInfoByProducts : StandardRequest {
        
        private string transactionIdField;
        
        private int productIdField;
        
        private string currencyField;
        
        private float currencyRateField;
        
        private int amountField;
        
        private System.DateTime terminalDateField;
        
        private string[] valuesField;
        
        private int[] banknotesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float CurrencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
                this.RaisePropertyChanged("CurrencyRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime TerminalDate {
            get {
                return this.terminalDateField;
            }
            set {
                this.terminalDateField = value;
                this.RaisePropertyChanged("TerminalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public int[] Banknotes {
            get {
                return this.banknotesField;
            }
            set {
                this.banknotesField = value;
                this.RaisePropertyChanged("Banknotes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class PingRequest : StandardRequest {
        
        private int terminalStatusField;
        
        private int cashCodeStatusField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TerminalStatus {
            get {
                return this.terminalStatusField;
            }
            set {
                this.terminalStatusField = value;
                this.RaisePropertyChanged("TerminalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CashCodeStatus {
            get {
                return this.cashCodeStatusField;
            }
            set {
                this.cashCodeStatusField = value;
                this.RaisePropertyChanged("CashCodeStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class CurrenciesResult : StandardResult {
        
        private Currency[] currenciesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Currency[] Currencies {
            get {
                return this.currenciesField;
            }
            set {
                this.currenciesField = value;
                this.RaisePropertyChanged("Currencies");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class ProductResult : StandardResult {
        
        private Product[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("Products");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cashin/CashInService")]
    public partial class PingResult : StandardResult {
        
        private int commandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
                this.RaisePropertyChanged("Command");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CashInServerChannel : CashInTerminal.CashIn.CashInServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CashInServerClient : System.ServiceModel.ClientBase<CashInTerminal.CashIn.CashInServer>, CashInTerminal.CashIn.CashInServer {
        
        public CashInServerClient() {
        }
        
        public CashInServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CashInServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CashInServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CashInServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicKey() {
            return base.Channel.GetPublicKey();
        }
        
        public CashInTerminal.CashIn.AuthResult InitTerminal(int terminalId, string authKey, string publicKey) {
            return base.Channel.InitTerminal(terminalId, authKey, publicKey);
        }
        
        public CashInTerminal.CashIn.PingResult Ping(CashInTerminal.CashIn.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public CashInTerminal.CashIn.StandardResult CommandReceived(CashInTerminal.CashIn.StandardRequest request) {
            return base.Channel.CommandReceived(request);
        }
        
        public CashInTerminal.CashIn.ProductResult ListProducts(CashInTerminal.CashIn.StandardRequest request) {
            return base.Channel.ListProducts(request);
        }
        
        public CashInTerminal.CashIn.CurrenciesResult ListCurrencies(CashInTerminal.CashIn.StandardRequest request) {
            return base.Channel.ListCurrencies(request);
        }
        
        public CashInTerminal.CashIn.StandardResult Payment(CashInTerminal.CashIn.PaymentInfoByProducts request) {
            return base.Channel.Payment(request);
        }
        
        public CashInTerminal.CashIn.StandardResult Encashment(CashInTerminal.CashIn.Encashment request) {
            return base.Channel.Encashment(request);
        }
    }
}
